### ISSUE TITLE
templates missing in 0.4.7 release

### ISSUE THREAD

**Issue by bikeshedder** [mbi/django-simple-captcha#100]
The 0.4.7 release on PyPI is missing the templates directory. Therefore rendering this version unuseable.

**Comment by asnelzin** [comment]
+

**Comment by mbi** [comment]
Sorry for this, just released 0.4.8 to address this issue.

**Comment by asnelzin** [comment]
Thanks for fast response! :thumbsup:

**Comment by bikeshedder** [comment]
:+1: Thanks a lot!

**Comment by brianmay** [comment]
Still missing the testproject/templates directory...

**Comment by mbi** [comment]
So it is :(  Just released 0.5.0 with all the missing dependencies.

**Comment by brianmay** [comment]
Sorry to be a pain, however this still has some problems. Now you include too many files :-(.

* *.pyc files are not needed, and there are some *.pyc files which are included with no corresponding *.py file.

* testproject gets installed to the python modules directory is testproject - this is really not appropriate.

* .DS_Store files not required.

* Probably should not include docs/_build - these files aren't really source files.

* Debian policy is that original source code is required for all JavaScript, not minified files, which cannot be edited as source. Such as `testproject/htmlcov/*.min.js` - as this is testproject only suspect these files could be replaced with the non-minified version. Are you happy to do so?

**Comment by mbi** [comment]
@brianmay yes, MANIFEST.in needed some polishing (in ea9c16a0a66a687d9f042ce7e14d74b2ec6c6592) 

* `pyc`, `.DS_Store` files and `docs/_build` dir are excluded
* `htmlcov` shouldn't be included in the first place (excluded)
* `testproject` gets installed to the python modules directory: I think it's important to ship a test project, what is the best practice here? Do you have an example of other django apps included in Debian?

**Comment by brianmay** [comment]
For the last point, typically I have seen two solutions on this:

1. You move testproject to under captcha, and the tests now run under the `captcha.testproject` namespace.

2. You continue distributing the testproject as is with the source code and the PyPI code, however you do not attempt to install it as part of setup.py

The problem of course with installing a top level module called "testproject" is if you have two projects that both install a module called "testproject" they will clash with each other.

**Comment by mbi** [comment]
Ok d167014 should take care of this.

**Comment by brianmay** [comment]
Ok, thanks.

Will have a look ASAP, possibly tomorrow my timezone now.

**Comment by brianmay** [comment]
Looks pretty good to me. Thanks.

**Comment by mbi** [comment]
Sweet thanks. I'll release this as a new version to pypi later today.

**Comment by mbi** [comment]
ooookay, 0.5.1 is out, hopefully this one will stick.
