### ISSUE TITLE
IOError: [Errno 13] Permission denied: u'/usr/lib/python2.7/site-packages/captcha/migrations/0003_captchastore.py'

### ISSUE THREAD

**Issue by molavy** [mbi/django-simple-captcha#101]
python manage.py migrate
/home/user/workspace/proj/proj/urls.py:235: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  url(r'^captcha/', include('captcha.urls')),

Operations to perform:
  Apply all migrations: appplan_payan_tarh, captcha, admin, sessions, auth, appplan_markazdavar, contenttypes, appplan_moavenat, apporgan, appplan, appuser
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
user@localhost:~/workspace/proj$ python manage.py makemigrations
/home/user/workspace/proj/proj/urls.py:235: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  url(r'^captcha/', include('captcha.urls')),

Migrations for 'captcha':
  0003_captchastore.py:
    - Create model CaptchaStore
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib64/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/lib64/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib64/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib64/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/usr/lib64/python2.7/site-packages/django/core/management/commands/makemigrations.py", line 150, in handle
    self.write_migration_files(changes)
  File "/usr/lib64/python2.7/site-packages/django/core/management/commands/makemigrations.py", line 179, in write_migration_files
    with open(writer.path, "wb") as fh:
IOError: [Errno 13] Permission denied: u'/usr/lib/python2.7/site-packages/captcha/migrations/0003_captchastore.py'

**Comment by mbi** [comment]
Yes, makes sense, you can't create new migrations in your installed app package. (in /usr/lib/) 
Also, which version of Django and django-simple-captcha?
Can you please paste the output of `pip freeze`

**Comment by molavy** [comment]
django 1.9
django-simple-captcha-0.5.1
i can't understand why it try save migrations into /usr/lib/...
that seems a wrong place
or docs needs update

**Comment by mbi** [comment]
well, `makemigrations` will save the migrations in the migrations folder of the installed app, which in your case resides in /usr/lib/python2.7, i.e. you installed django-simple-captcha in the global system-wide site-packages. How did you install it by the way? Is your project running in a virtual-env?

As a matter of fact, you shouldn't need to run makemigrations at all in the first place.

All in all, this really looks like a installation / system issue, most likely not a bug.

**Comment by molavy** [comment]
but what about django simple history module
it also require create it own tables
it also installed in /usr/lib/...
but it don't create it migrations into /usr/lib/...
