### ISSUE TITLE
Use Captcha with two different CAPTCHA_LENGTH

### ISSUE THREAD

**Issue by caligoig** [mbi/django-simple-captcha#109]
I have two forms on two different pages where I would like to use Captcha, 
On form A, I wanna have captcha length of 5 chars, but on form B I would like to have captcha length of 8 chars displayed. How can I do that? 
Thanks

**Comment by mbi** [comment]
Hi, I'm sorry this can't be done at the moment because the function that generates the challenge is configured in the settings and cannot (yet) be passed as an argument to the field constructor (which would probably make sense).

**Comment by caligoig** [comment]
Thanks

**Comment by mbi** [comment]
Actually this was quite simple to implement, if you are willing to test-drive it I've pushed a separate branch https://github.com/mbi/django-simple-captcha/tree/callable-generators that will let you pass a per-field generator, i.e. : 

     captcha = CaptchaField(generator='path.to.generator_function') 

So if you define two [generators functions](https://django-simple-captcha.readthedocs.io/en/latest/advanced.html#roll-your-own) you can pass those to your two fields and you should be set.

**Comment by caligoig** [comment]
Thanks, 
I am gonna try it and will let you know
This is prefect

**Comment by caligoig** [comment]
Tried it and it is working :-)
Only thing that wasn't working as expected was captcha-refresh url, it was still using old generator from settings, but I managed to override that by adding my view to generate refresh using new generator. 
Thanks for helping
