### ISSUE TITLE
captcha don't take effect in some cases

### ISSUE THREAD

**Issue by phith0n** [mbi/django-simple-captcha#112]
HI, I found a bug with django-simple-captcha validator. And it is a common bug in some Python web framework.
My login form:

```
from django.contrib.auth.forms import AuthenticationForm

class MyAuthenticationForm(AuthenticationForm):
    captcha = CaptchaField(label='验证码',
                           output_format='<div class="row"><div class="col-sm-8">%(text_field)s %(hidden_field)s</div><div class="col-sm-4 padding">%(image)s</div></div>')

    class Meta:
        fields = [
            'email',
            'password',
            'captcha',
        ]
```

The AuthenticationForm.clean and the CaptchaField.clean, both of them will be executed at the same time. So when I render the MyAuthenticationForm.errors, the two errors will be shown tegether:

![sp161007_212305](https://cloud.githubusercontent.com/assets/5711185/19191271/4c98a950-8cd4-11e6-85be-4550f2084115.png)

So attackers would know his password attempt is successful or failed, although his captcha is error.

Even I don't show the errors, if the password validator spend more time than the captcha validator, it may also allow an attacker to know if the password is correct.

**Comment by mbi** [comment]
Yes, I see your point, but I don't think this can be fixed by django-simple-captcha alone, rather in Django itself. Or have two separate fields: solve a captcha first, then have a second form where you can login?
