### ISSUE TITLE
Which version for Django 1.6

### ISSUE THREAD

**Issue by beamkiller** [mbi/django-simple-captcha#117]
Hi Marco,

Can you help me which version from commits section should I download for my client who is still using Django 1.6. So which version is fully compatible with 1.6 version.

Thanks,
Peter.

**Comment by mbi** [comment]
Hi Peter, according to [this commit](https://github.com/mbi/django-simple-captcha/commit/2cd5054cd075669109b872f13421c899ce7fd71a), starting from 0.4.7 Django 1.7 is required, so I'd say 0.4.6 is the last one supporting 1.6.

Cheers,
–m
