### ISSUE TITLE
Field attribute error on Django 1.11

### ISSUE THREAD

**Issue by lzanuz** [mbi/django-simple-captcha#118]
build_attrs() takes from 1 to 2 positional arguments but 3 were given
Django Version:	1.11
Exception Type:	TypeError
Exception Value:	
build_attrs() takes from 1 to 2 positional arguments but 3 were given
Exception Location:	captcha/fields.py in render

**Comment by mbi** [comment]
Yes, I know. A Django 1.11 compatible release is ready, I'll push it to the cheese shop today!

**Comment by mbi** [comment]
Right, so this was fixed in [v0.5.5](https://github.com/mbi/django-simple-captcha/releases/tag/v0.5.5).
