### ISSUE TITLE
Audio files not supported on Safari 11 desktop #25

### ISSUE THREAD

**Issue by po5i** [mbi/django-simple-captcha#123]
I got the response DOMError `{name: "NotSupportedError", message: "The operation is not supported."}` on the following HTML when I play the captcha sound:

    var a = new Audio("https://xxxxxxxxxx.com/captcha/audio/52d3c6188d2fb733480ce2198a7fde4ec1e9d579");
    // var a = new Audio("https://www.w3schools.com/html/horse.mp3"); // works!
    // var a = new Audio("http://www.wavsource.com/snds_2017-09-17_1751672946049674/movie_stars/deniro/meet_parents_bring_u_down.wav");  // works!
    var promise = a.play();
    promise.catch(error => {
    	console.log(error)
    })
    .then(() => {
    	console.log('success, it played!')
    })

**Comment by mbi** [comment]
Okay fixed, good catch! Could you please test against HEAD and confirm this is ok?

**Comment by po5i** [comment]
Thanks! tested against HEAD successfully on Chrome and Safari.
After this will you release it on PIP?



CC @jorlusal

**Comment by mbi** [comment]
I'll probably release the next version to PyPi when Django 2.0 lands, probably in a few weeks. 

In the meantime you can maybe `pip install -e git+https://github.com/mbi/django-simple-captcha.git#egg=django-simple-captcha-dev`
