### ISSUE TITLE
Use standard rendering of widgets

### ISSUE THREAD

**Issue by ziima** [mbi/django-simple-captcha#128]
By default, rendering should use standard templates for individual widgets. The additional attributes should be added through `Widget.attrs`.

Current status does not render correctly the HTML5 `required` attribute, and I expect similar problem applies to other `attrs` which may be passed to widget instances.

**Comment by mbi** [comment]
Thanks for the pull request!

**Comment by ziima** [comment]
Thanks for merge.

Seems that `resolve` is a keyword for closing related issues :-/ I had to open #134 to continue.
