### ISSUE TITLE
Use standard rendering of widgets (vol. 2)

### ISSUE THREAD

**Issue by ziima** [mbi/django-simple-captcha#134]
By default, rendering should use standard templates for individual widgets. The additional attributes should be added through `Widget.attrs`.

Current status does not render correctly the HTML5 `required` attribute, and I expect similar problem applies to other `attrs` which may be passed to widget instances.

_Recreated due to accidental closure of #128 from #133._

**Comment by mbi** [comment]
Thank you for this!

So… I'm a bit lost, what does this do that your previous fix didn't? Also, do we need to update the documentation (I'm thinking: the [configuration section](http://django-simple-captcha.readthedocs.io/en/latest/advanced.html) and maybe a new section explaining how to change / override the rendering template?)

Also, am I correct in understanding that for Django < 1.11 the templates from `captcha/*.html` are used, and on Django 1.11 the rendering is done with `captcha/widgets/captcha.html`?

**Comment by ziima** [comment]
My previous fix just cleaned the implementation of the widgets. This change actually supports the widget templates introduced in Django 1.11.

Good point on docs, I'll update those.

> Also, am I correct in understanding that for Django < 1.11 the templates from `captcha/*.html` are used, and on Django 1.11 the rendering is done with `captcha/widgets/captcha.html`?

Exactly.

**Comment by ziima** [comment]
Any other update or request?

**Comment by mbi** [comment]
@ziima ah, sorry, been busy, will try to review and merge this weekend!

**Comment by mbi** [comment]
Sorry again for sitting on this so long and thank you again for your contributions!

**Comment by ziima** [comment]
Thanks for merging. Any chance to see a new release soon?

**Comment by mbi** [comment]
Sure, no problem, just release 0.5.7

**Comment by ziima** [comment]
Thanks
