### ISSUE TITLE
TemplateDoesNotExist

### ISSUE THREAD

**Issue by gandriyko** [mbi/django-simple-captcha#145]
When 
settings.py contains 

```python

FORM_RENDERER = 'django.forms.renderers.Jinja2'
```
Form with captcha field raises Exception
```python
TemplateDoesNotExist at /
'captcha/widgets/captcha.html'


Template-loader postmortem
Django tried loading these templates, in this order:
Using engine djangoforms:
    This engine did not provide a list of tried templates.


```

**Comment by mbi** [comment]
@ziima ditto: this _might_ be in the realm of your recent changes, what is your take on this? Thank you!

**Comment by gandriyko** [comment]
Everything is fine on django-simple-captcha==0.5.6, 
but in django-simple-captcha==0.5.7 something seems to bee broken.

**Comment by ziima** [comment]
I have not included a Jinja2 templates for the captcha widget. We can certainly add those, but when I digged in a bit, I found out the tests doesn't pass with Jinja2 templates at all.

@mbi: Are Jinja2 templates supported at all? Should we add test environment with Jinja2 templates?

**Comment by mbi** [comment]
@ziima well, Django supports Jinja2, I would have expected django-simple-captcha to do so, too. 

@gandriyko says that django-simple-captcha 0.5.6 was fine, so it seems it's linked to your recent changes.

**Comment by ziima** [comment]
I've tried adding

    FORM_RENDERER = 'django.forms.renderers.Jinja2'

to the test settings and the tests didn't pass. Maybe the problem is in the tests, I haven't investigated too deeply.

**Comment by ziima** [comment]
OK, in #145 I've added a jinja2 template for captcha widget and a jinja2 environment into tox.

**Comment by mbi** [comment]
Thank you @ziima! 
@gandriyko I just pushed 0.5.8, this should fix the problem!

**Comment by mbi** [comment]
Yes, that's my fault, sorry, I'll repackage this properly and release 0.5.9.

@ziima I was wondering, is there a good reason to have the `jinja2` folder inside `captcha`? Shouldn't it live in e.g. `captcha/templates/jinja2`?

**Comment by mbi** [comment]
@gandriyko Okay, fixed in 0.5.9

**Comment by gandriyko** [comment]
Yes, everything  is OK. Thank you.

They should live in e.g. **captcha/jjinja2** due:


```python
class Jinja2(BaseEngine):

    app_dirname = 'jinja2'

    def __init__(self, params):
```

**Comment by ziima** [comment]
> I was wondering, is there a good reason to have the jinja2 folder inside captcha? Shouldn't it live in e.g. captcha/templates/jinja2?

@mbi As @gandriyko stated, the default directory for jinja2 templates is `jinja2`.
