### ISSUE TITLE
Add support for Pillow 5.1.0

### ISSUE THREAD

**Issue by lorddaedra** [mbi/django-simple-captcha#147]
django-simple-captcha 0.5.8 has requirement Pillow<5.0,>=2.2.2, but you'll have pillow 5.1.0 which is incompatible.

**Comment by mbi** [comment]
I don't understand, what's wrong with Pillow < 5.0?

**Comment by mbi** [comment]
Pillow 5.1.0 is toxic: https://github.com/python-pillow/Pillow/issues/3068 

As soon as 5.1.1 is release everything should be back and dandy, but for the time being 5.1.0 is a nono.
