### ISSUE TITLE
Fix DeprecationWarning: CaptchaTextInput's output_format argument is deprecated in favor of widget's template_name.

### ISSUE THREAD

**Issue by lorddaedra** [mbi/django-simple-captcha#148]
```/usr/local/lib/python3.6/site-packages/captcha/fields.py:99: DeprecationWarning: CaptchaTextInput's output_format argument is deprecated in favor of widget's template_name.```

**Comment by mbi** [comment]
Sorry, I don't understand. This deprecation warning means *you* have to change your settings according to [the documentation](https://django-simple-captcha.readthedocs.io/en/latest/advanced.html?highlight=template_name#rendering).
