### ISSUE TITLE
Audio captha does not speek '+'

### ISSUE THREAD

**Issue by geirkairam** [mbi/django-simple-captcha#156]
If CAPTCHA_CHALLENGE_FUNCT = 'captcha.helpers.math_challenge' is enabled in settings the '+' is not spoken. 
Users may not know what they are supposed to do.

**Comment by thomasDOTwtf** [comment]
I would really like this pull request to be merged.

**Comment by mbi** [comment]
Merged, thank you for the issue and the PR, @geirkairam
