### ISSUE TITLE
render() got an unexpected keyword argument 'renderer'

### ISSUE THREAD

**Issue by dhcn** [mbi/django-simple-captcha#159]
This is almost certainly because of this backwards-incompatible change in Django 2.1:

Support for Widget.render() methods without the renderer argument is removed.
https://stackoverflow.com/questions/52039654/django-typeerror-render-got-an-unexpected-keyword-argument-renderer

**Comment by mbi** [comment]
Are you sure you're using an up to date version? `render` does [indeed accept](https://github.com/mbi/django-simple-captcha/blame/3fc65e977bb2f12c276351a19b7c6b7b6558ea55/captcha/fields.py#L166) a `renderer` argument.

What is the output of this? You should have 0.5.9

```
import captcha
captcha.VERSION
```

**Comment by mbi** [comment]
Likely wrong version installed, closing.
