### ISSUE TITLE
HttpResponseRedirect(reverse('login')) ,django-simple-captha Pictures cannot be loaded

### ISSUE THREAD

**Issue by z3630275** [mbi/django-simple-captcha#161]

**Comment by z3630275** [comment]
HttpResponseRedirect(reverse('login')) ,django-simple-captha pictures cannot be loaded

**Comment by mbi** [comment]
I'm sorry, can you be more specific?

**Comment by z3630275** [comment]
After using the intermediate key to intercept the global login, the authentication code prompts that the picture cannot be loaded.

**Comment by mbi** [comment]
Can you share your code?

**Comment by mbi** [comment]
Closing because no answer, I can't help if you don't explain what's going on, sorry.
