### ISSUE TITLE
CAPTCHA_TEST_MODE no effect in settings.py

### ISSUE THREAD

**Issue by ohlr** [mbi/django-simple-captcha#163]
setting `CAPTCHA_TEST_MODE = True` does not show any effect when specified in `settings.py`.

all other settings I am using are working . Can anyone confirm this issue?

django-ranged-response==0.2.0
django-simple-captcha==0.5.10
Pillow==5.4.1
Python 3.6.7
Django 2.1

**Comment by gdrubich** [comment]
Yes, I'm trying to automatize a test for a form in my project. I set the variable on True but the form keeps retrieving me an "Invalid CAPTCHA" error.

**Comment by Don-Leopardo** [comment]
Does everyone around here have the same issue? It's so painfull, you set it in True and it keeps retrieving "Invalid CAPTCHA" like there's no tomorrow! I hate it! Is there any solution?

**Comment by mbi** [comment]
Guys, so sorry about this, just found the bug. Give me a minute and I'll release a fixed version…

**Comment by mbi** [comment]
Alright, there you go, [0.5.11](https://pypi.org/project/django-simple-captcha/0.5.11/) should fix this.

**Comment by gdrubich** [comment]
Ok, caling "form.is_valid()" still returns False with the "Invalid CAPTCHA" error. So it's still unsolved.

**Comment by ohlr** [comment]
Can confirm, I just tested it - it still does not work

**Comment by mbi** [comment]
Hmm, can you please test it manually? That's what I did and it *was* working!

**Comment by Don-Leopardo** [comment]
Tsss, I was very happy when I saw your comment saying "0.5.11 should fix this"... I was so exited... Then I tested it... And it was frustrating, it was... just frustrating... There was it... The "Invalid CAPTCHA" error again and again.

**Comment by ohlr** [comment]
What do you mean test manually? run the testsuite? I installed the package via pip

**Comment by gdrubich** [comment]
Yes, in fact all my tests have been manual. I'm creating a dict with the form data, passing the captcha params like this:
`form_data = {u'phone_number': '+540000000000', u'first_name': Test', u'last_name': u'Test', u'email': 'info@test.com', u'message': u'Test msg.', 'captcha_0': '0231k23sdasjdasd', u'captcha_1': u'ASDASDASDASD'}`
I named the keys this way because that's how I saw they were created on request.POST

**Comment by mbi** [comment]
> What do you mean test manually? run the testsuite? I installed the package via pip

I mean, manually going to a page with the form, submit the form with "passed" in the captcha field, check if this works on not.

**Comment by mbi** [comment]
> `u'captcha_1': u'ASDASDASDASD'}`

Is this what you submit? The [documentation](https://django-simple-captcha.readthedocs.io/en/latest/advanced.html#captcha-test-mode) clearly states that you need to pass "PASSED" (any case) for the test to pass.

**Comment by ohlr** [comment]
Ok, in the browser it works for me too - I overread the PASSED - sorry

**Comment by gdrubich** [comment]
So sorry, same mistake. Thanks for the patience and the quick answer.

**Comment by mbi** [comment]
Ah, cheers, all good. I hope that the next person having this issue will find this thread, then ;-)

**Comment by Goury** [comment]
Found it.
Clarity of the documentation can be improved.
An example could save an hour of my life.

Cheers.
