### ISSUE TITLE
will fail with upcoming django versions

### ISSUE THREAD

**Issue by devkral** [mbi/django-simple-captcha#165]
django-simple-captcha uses python\_2\_unicode\_compatible from django. This will be removed in the next major django release (I test against the git version of django).

 File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/captcha/models.py", line 4, in <module>
    from django.utils.encoding import python\_2\_unicode\_compatible
ImportError: cannot import name 'python\_2\_unicode\_compatible'

**Comment by mbi** [comment]
Okay, I'm not too fussed about this: simple-captcha supports the latest *released* version of Django and a few versions back. We only usually start testing against new versions of Django as soon as they release the first alpha. 

That said, if this is an easy fix that is backwards compatible with all currently supported versions of Django (1.8 through 2.2), I'm more than happy to accept a pull request!

**Comment by devkral** [comment]
Me neither. It is just a reminder for the future. Something which is good to have in the development version because else-wise it is fogotten

**Comment by devkral** [comment]
fix submitted (see pull request #166 )

**Comment by devkral** [comment]
anyway the test matrix should be cleaned up (remove django versions <1.11) Shall I drop some patches?

**Comment by mbi** [comment]
Thanks for the issue and the PR!

I've added (bfd3627) tests against Django3 (the current master, actually) to the matrix. I'd rather we maintain compatibility against old versions of Django if we can, as long as it doesn't impact the codebase. (i.e. if it doesn't hurt to do so)

Cheers!

**Comment by devkral** [comment]
Thanks for the fast merge!
May I make a recommendation? Don't call it django3 but django master. It reflects the fact that it is build against the master branch.

**Comment by mbi** [comment]
Well, it *is* Django3 to all effects, isn't it? As soon as Django 3 alpha1 is released I'll replace the path in the toxfile.
