### ISSUE TITLE
don't read words dictionary as binary?

### ISSUE THREAD

**Issue by grasshoppermouse** [mbi/django-simple-captcha#167]
Should this line:

`fd = open(settings.CAPTCHA_WORDS_DICTIONARY, 'rb')`

instead be:

`fd = open(settings.CAPTCHA_WORDS_DICTIONARY, 'r')`

`'rb'` doesn't work for me, but `'r'` does.

python 3.7.3, django 2.2.3

**Comment by mbi** [comment]
Well spotted, thank you! 🍰
