### ISSUE TITLE
a question about installation of django-simple-captcha

### ISSUE THREAD

**Issue by Ivan-Ji** [mbi/django-simple-captcha#168]
I installed `captcha` with Python at first and didn't find wrong in my codes, but later when I generated `requirements. txt`, I found that `django-simple-captcha` was to be installed. After installation of `django-simple-captcha`, the contents of the `captcha/models.py` file disappeared.

**Comment by Ivan-Ji** [comment]
Although I later opened the file, I copied the `captcha/models.py` content from GitHub to the local site-packages for use.

**Comment by mbi** [comment]
Sorry, closing as this doesn't make sense, also none of your two comments are actually a question :)
