### ISSUE TITLE
Deprecation warning on Django 3.0 beta

### ISSUE THREAD

**Issue by jannh** [mbi/django-simple-captcha#173]
In Django 3.0, the function ugettext_lazy is deprecated, since it is a synonym with gettext_lazy in python3. You can refer to the release notes.

ugettext_lazy is used in captcha/fields.py and in captcha/tests/tests.py 

How would you proceed here? Since python 2 is EOL in about 2 months, do you think it would be a good idea to drop support for python 2 and to just replace the two instances of ugettext_lazy?

**Comment by mbi** [comment]
Thanks, fixed in e5125aa.
