### ISSUE TITLE
how to integrate to default django admin login template?

### ISSUE THREAD

**Issue by gr01d** [mbi/django-simple-captcha#175]
The documentation is a bit confusing, how do I integrate this to the default django login view. (form.as_p)

**Comment by mbi** [comment]
This isn't really related to Django Simple Captcha at all, but here is the idea: define a [custom login form](https://stackoverflow.com/questions/55369645/how-to-customize-default-auth-login-form-in-django/55369752#55369752) with a [CaptchaField](https://django-simple-captcha.readthedocs.io/en/latest/usage.html#adding-to-a-form), then instruct the `LoginView` to use your custom form (first link).

This should work.

**Comment by gr01d** [comment]
for anyone having the same problem, this is a good reference: https://stackoverflow.com/questions/52026453/django-custom-login-form-is-valid-but-no-error/

**Comment by gr01d** [comment]
This project adds simple captcha to the default django admin.
https://github.com/a-roomana/django-multi-captcha-admin
