### ISSUE TITLE
Database Concerns

### ISSUE THREAD

**Issue by 9mido** [mbi/django-simple-captcha#183]
A main issue I have is needing to store the captcha in the database each time a user comes to the page. The expiration date is too long to be stored in the database. It would be nice to set the expiration to a custom time to be able to automatically delete the data from settings.py. 

Another point of discussion is why even store the captcha in the database at all? Just seems like a bottleneck forcing websites with millions of page views a day to delete the data which can be quite costly to the database if there are a lot of records. I see that there is the pool option in the docs, but that makes it even easier for an attacker to guess the captcha if it doesn't keep changing. 

I see that there are pull requests that try to address this type of issue which has not been approved or worked on for years which is also concerning.

Storing in session might be best as opposed to the cache since cache can be a problem if there are hardware limitations. 

What would the cron job / postgres command / shell script alternative be to deleting the database items on a regular basis?

Otherwise maybe redesign the app to not need database storage and hidden input fields at all?

**Comment by mbi** [comment]
> A main issue I have is needing to store the captcha in the database each time a user comes to the page. The expiration date is too long to be stored in the database. It would be nice to set the expiration to a custom time to be able to automatically delete the data from settings.py.

This has always been the case, see [CAPTCHA_TIMEOUT](https://django-simple-captcha.readthedocs.io/en/latest/advanced.html#captcha-timeout) (defaults to 5 minutes). You can manually clean expired captchas via the included management command. 

So assuming you're not changing the default timeout and that you run the command every five minutes, you'll get at most ~ 3'500 entries to delete (assuming one million daily visitors hitting a page with a captcha). 

At approx 2.5k per row (see below), that'd cost you up to 8.7MB in your database, including data and indexes. I'm sure your multi-million visitors / day website can handle 9 megs of DB storage? :smirk: 

 
```
              metric               | bytes/ct | bytes_pretty | bytes_per_row 
-----------------------------------+----------+--------------+---------------
 core_relation_size                |     8192 | 8192 bytes   |           122
 visibility_map                    |        0 | 0 bytes      |             0
 free_space_map                    |    16384 | 16 kB        |           244
 table_size_incl_toast             |    24576 | 24 kB        |           366
 indexes_size                      |   147456 | 144 kB       |          2200
 total_size_incl_toast_and_indexes |   172032 | 168 kB       |          2567
 live_rows_in_text_representation  |     5956 | 5956 bytes   |            88
```

**Comment by 9mido** [comment]
@mbi thanks for the clarification. It took me some time to figure out but I was able to. The docs didn't have any examples of a cron job or anything so it took me a few days to figure out.
