### ISSUE TITLE
do not overwrite "captcha" files

### ISSUE THREAD

**Issue by blshkv** [mbi/django-simple-captcha#185]
I came to a software (seafile) which require both 
https://pypi.org/project/django-simple-captcha/
 and
https://pypi.org/project/captcha/

packages. Apparently, django-simple-captcha installs files into the same location, a "captcha" folder overwriting other package's files.

Please install files into a unique folder name (django-simple-captcha).

**Comment by mbi** [comment]
No can do. `django-simple-captcha` is not a valid Python module name and changing names would break the install of everyone relying on the package name being `captcha`.

**Comment by blshkv** [comment]
This is disappointing. You should design your tool better and consider changing it in the future.
