### ISSUE TITLE
Incompatible to Pillow v.8.3.1

### ISSUE THREAD

**Issue by aDramaQueen** [mbi/django-simple-captcha#202]
Hello,
today we discovered, that this app breaks an entiere Django project if you're using current Pillow version 8.3.1.
The application then just stops on boot with exit code -1. No exception, no error. Just exit code -1.

Rollback to Pillow 8.3.0 solved this problem.

**Comment by mbi** [comment]
Pillow is not pinned in the dependencies, so the test suite runs with the latest version by default, and 8.3.1 [seems to be perfectly fine](https://github.com/mbi/django-simple-captcha/runs/3130816475?check_suite_focus=true).

![image](https://user-images.githubusercontent.com/131808/126592397-da67e347-3605-4234-acc7-46cc8933043e.png)


So, what version of Python, Django, and OS are experiencing this on?

**Comment by aDramaQueen** [comment]
Hmm..., this is odd.
You're right. I tried it on another machine today. And it works there. Yesterday on the 2 machines of other the developers it didn't work.
What really puzzeled me was the exit code -1. This was very frustrating since you don't get any usefull information. You just see it doesn't work. So we did it like in the good old days with some print outs. We discovered we're reaching the urls.py from the project core. By simple trial & error we saw that the exit code -1 was thrown when the URLs from captcha were integrated.
![grafik](https://user-images.githubusercontent.com/52710085/126614765-1c4924d9-7f4f-45e3-b093-c23a63571757.png)
At that time we knew it has to be captcha. After some more time we narrowed it down to pillows 3.8.1 & tried a reverse to the last known version were it worked. This was 3.8.0.
But as said before, on the 3rd machine today it works?!? I think then this is not really an issue of captcha and/or pillow. Maybe it's machine specific.
By the way, all machines run Windows 10. One dev uses Pycharm, the other IntelliJ with Python plugin.
This is our requirements: [requirements.txt](https://github.com/mbi/django-simple-captcha/files/6861162/requirements.txt)

If I discover what's going on, I maybe reopen this issue...

**Comment by mbi** [comment]
What wsgi server is this on? mod_wsgi / gunicorn / ?

Also, in my experience random exit code -1 crashes could be related to out of memory issues. Check your server / machine logs!

**Comment by aDramaQueen** [comment]
This is not running on any server. This was on the developer machines. What's Djangos standard dev server? I think it's Grunt?!?

**Comment by aDramaQueen** [comment]
OK

**Comment by mbi** [comment]
Not a django-simple-captcha issue, closing.
