### ISSUE TITLE
Publish wheel

### ISSUE THREAD

**Issue by vsalvino** [mbi/django-simple-captcha#207]
Would you be able to publish wheels (.whl) in addition to the source distributions? One advantage to wheels from the python infrastructure standpoint is they install much faster as PyPI is able to pre-resolve the dependencies. And if your package is "pure" python (no C extensions) then building a wheel is very simple.

The command to build both source distribution and wheel is:

```
$ pip install wheel
$ python setup.py sdist bdist_wheel
```

Then upload both as usual to PyPI. I would be happy to help if needed, just let me know!

For more into see: https://pythonwheels.com/

**Comment by mbi** [comment]
0.5.15 published with wheel. :+1:
