### ISSUE TITLE
Missing migration after removal of id field in model

### ISSUE THREAD

**Issue by atodorov** [mbi/django-simple-captcha#208]
django-simple-captcha 0.5.15 contains this change: https://github.com/mbi/django-simple-captcha/pull/206

which results in `./manage.py makemigrations --check` creating a new migration which isn't supplied with django-simple-captcha, see logs at https://github.com/kiwitcms/Kiwi/runs/5438133900?check_suite_focus=true. 

Note: I am testing with Django 4.0.3.

**Comment by mbi** [comment]
Thanks for the heads-up, release follows in a few minutes.
