### ISSUE TITLE
English translation created from Spanish ones

### ISSUE THREAD

**Issue by tpazderka** [mbi/django-simple-captcha#209]
The latest release adds English translations to the package, but they are created from Spanish input files which causes obvious problems :)

**Comment by mbi** [comment]
:facepalm: 

thanks for the heads-up, let me fix that...

**Comment by mbi** [comment]
0.5.17 pushed, apologies for the f**-up.

**Comment by tpazderka** [comment]
Muchas gracias, funciona ahora!
