### ISSUE TITLE
Wrong language header in English translation

### ISSUE THREAD

**Issue by antonialoytorrens** [mbi/django-simple-captcha#211]
https://github.com/mbi/django-simple-captcha/blob/master/captcha/locale/en/LC_MESSAGES/django.po#L1

It should be `# django-simple-captcha English translation.`, isn't it?

**Comment by mbi** [comment]
It probably should, but also, I'm not sure if it's worth changing?
A PR would be welcome, if it's a big deal to you. :pray:
