### ISSUE TITLE
Looking for examples

### ISSUE THREAD

**Issue by kw-andy** [mbi/django-simple-captcha#212]
Hi,

This is my current captcha (see image [here](https://i.imgur.com/O11eHGq.png)).

I'm trying to have something like [this](https://camo.githubusercontent.com/49753b094ca77aac3c60cb53e7055249f60bbcd7b64c00db0f35aae7d4322b9f/687474703a2f2f646a616e676f2d73696d706c652d636170746368612e72656164746865646f63732e696f2f656e2f6c61746573742f5f696d616765732f63617074636861332e706e67) with an error color code if it is not doing it correctly. 

You do not have many examples, which can be used to tweak simple captcha.

Would you have a few to provide with, please?

Cheers,
Andy

**Comment by mbi** [comment]
Hi Andy. The formatting of the error message, if the captcha resolution failed, is really just handled by Django and your front-end framework of choice, and not at all by django-simple-captcha. 

I suggest you play around with integrating e.g. [Bootstrap](https://django-bootstrap-v5.readthedocs.io/en/latest/) into your project and the error styles should "just work" :tm:. 

Hope this helps a little.
