### ISSUE TITLE
django 4 not suported

### ISSUE THREAD

**Issue by kazem3d** [mbi/django-simple-captcha#213]
django 4 not suported

**Comment by mbi** [comment]
Our test suite covers Django  2.2 through 4.1.  You’ll have to be more specific on what is not working, please.

**Comment by kazem3d** [comment]
django-simple-captcha needs "smart_text" and in django 4 smart_text is
removed from the utils.encoding

**Comment by mbi** [comment]
The only reference to smart_text is here: https://github.com/mbi/django-simple-captcha/search?q=smart_text

We rename-import `smart_str` as `smart_text` for backwards compatibility, but we don't really import smart_text from Django.
