### ISSUE TITLE
Wheel for 0.5.14 on pypi.python.org inconsistent

### ISSUE THREAD

**Issue by StefanBeyer** [mbi/django-simple-captcha#214]
I just noticed that the wheel for 0.5.14 on [PyPI](https://pypi.org/project/django-simple-captcha/0.5.14/#files) ([direct link](https://files.pythonhosted.org/packages/7c/dc/eabf438d0c22001907201094321cd4773e7855e1c1561883266c663cf54f/django_simple_captcha-0.5.14-py2.py3-none-any.whl)) is inconsistent with the source distribution and the code on GitHub. Especially, the code in the models.py file contains the id field, which is only introduced in 0.5.15:

``` python
class CaptchaStore(models.Model):
    id = models.AutoField(primary_key=True)
    challenge = models.CharField(blank=False, max_length=32)
    ...
```

I noticed because we ran into the same issues on 0.5.14, as described here #208. According to #207 it seems like that wheels were first built for 0.5.15, so I guess this upload might be faulty?

**Comment by mbi** [comment]
Hiya, thanks for noticing and bringing up the problem. 

Given that the current version on PyPI is 0.5.17, how big of a deal is this to you? I'm tempted to just remove the wheel file for that version and just offer the source distribution. 

What do you think?

**Comment by StefanBeyer** [comment]
Thanks for the quick response! Yes, removing the wheel would be perfectly fine for us.

**Comment by mbi** [comment]
Done, 0.5.14 now only has an egg and source. Thanks again for the heads-up

![image](https://user-images.githubusercontent.com/131808/186476093-d9803457-6559-4e2a-be47-69ae2d3b5e86.png)
