### ISSUE TITLE
Settings Configuration issue

### ISSUE THREAD

**Issue by ShrijanL** [mbi/django-simple-captcha#240]
- to use configurations like CAPTCHA_FONT_SIZE.. etc , they work when setup in settings file of django project.
- But does not work when initialized in django apps.py ( customize django settings on runserver command )

**Comment by mbi** [comment]
Could you please provide a test case or a small sample project to reproduce this?

**Comment by mbi** [comment]
Well, you're changing / assigning settings at runtime, Django's docs clearly state you can't do that.
https://docs.djangoproject.com/en/5.1/topics/settings/#altering-settings-at-runtime
