### ISSUE TITLE
Double id "id_captcha_0" on multicaptcha page. 

### ISSUE THREAD

**Issue by renta** [mbi/django-simple-captcha#37]
I have an app with 2 forms powered django-simple-captcha field on one page. They are put on the page with {{ my_form_1.captcha }} and  {{ my_form_2.captcha }} tags (just examples). Hidden fields with names captcha_0 have same ids "id_captcha_0".

This situation makes invalid html and confusions during ajax refresh of this fields.

**Comment by amtur8** [comment]
Haven't checked the code, but I'd need this to be corrected. Would it be possible and easy to add a prefix/suffix to generated ids ?

**Comment by mbi** [comment]
Okay, this should be fixed in version 0.4.4
