### ISSUE TITLE
Use multiple fonts

### ISSUE THREAD

**Issue by Matthias84** [mbi/django-simple-captcha#51]
Hi, I heard that using esp. different fonts within a captcha can drop down machine based OCR approaches [here for example](http://www.codinghorror.com/blog/2006/10/captcha-effectiveness.html).
So can you extend simple captcha to make use of a set of fonts, to make it robots a bit harder?

BTW. Thank you very much for your work, I really appreciate it, to avoid any 3rd party tracking widgets etc. :+1:

**Comment by inflrscns** [comment]
Just added a pull request with this feature, [right here.](https://github.com/mbi/django-simple-captcha/pull/88)

**Comment by mbi** [comment]
Done, thanks @inflrscns for the PR.

**Comment by Matthias84** [comment]
Thanks folks :-)

**Comment by inflrscns** [comment]
No problem, happy to contribute! : ]
