### ISSUE TITLE
math_challenge

### ISSUE THREAD

**Issue by isergey** [mbi/django-simple-captcha#77]
Hello! Some times captcha show math expression, for example: 2 * 2 =
But in real life, multiple operator is "x". Asterisk is more computer science symbol for multiple operation.
People who do not know can not understand this symbol

In this sample, * replace to x:
``` python
def math_challenge():
    operators = ('+', 'x', '-',)
    operands = (random.randint(1, 10), random.randint(1, 10))
    operator = random.choice(operators)
    if operands[0] < operands[1] and '-' == operator:
        operands = (operands[1], operands[0])
    challenge = '%d%s%d' % (operands[0], operator, operands[1])
    return '%s=' % (challenge), text_type(eval(challenge.replace('x', '*')))
```

**Comment by honsdomi** [comment]
Hello, I would to know if this project is still active. I have a school assignment to contribute to some open source project. I have used django-simple-captcha in my bachelor project so I thought I would contribute.

**Comment by mbi** [comment]
@honsdomi sure it's still active, please get in touch (marco@cruncher.ch) if you would like to discuss how you could contribute (instead of piggybacking open issues :trollface:)
