### ISSUE TITLE
App name collision with `django-recaptcha`

### ISSUE THREAD

**Issue by barseghyanartur** [mbi/django-simple-captcha#80]
Is there a chance you could rename the app name from `captcha` to `simple_captcha`? At the moment you can't use both `django-simple-captcha` and `django-recaptcha`.

Considering the fact that your package is named `django-simple-capcha` (and not `django-captcha`) the change sounds quite logical.

**Comment by mbi** [comment]
Uhm, that is rather unfortunate.

Now, why would _anyone_ install two distinct captcha handling apps at the same time?

That said, provided that django-simple-captcha has been first released almost a full year before django-recaptcha, has more forks, followers and stars on GitHub and that it *appears* to be more used on [djangopackages.com](https://www.djangopackages.com/grids/g/captcha/), why shouldn't django-recaptcha rename instead? ;-)

**Comment by barseghyanartur** [comment]
@mbi: It's not about who is bigger and older. It's about what's being logical and reasonable. The choices is yours and I find it unreasonable. Both of you, actually:

https://github.com/praekelt/django-recaptcha/issues/48

**Comment by mbi** [comment]
Sorry, I don't get it: renaming __either__ package would impose a backward incompatible change to anyone using them. 

To django-simple-captcha users, this would mean going over all the user code and change import paths, whereas I've been promoting a super stable API and upgrade path for ___years___.

And what for? Again, why would anyone use two distinct captcha apps in a single project? And if this is so important, the solution is to simply fork either package and do a 5 minute search and replace operation.
