### ISSUE TITLE
Wrong translation for  German

### ISSUE THREAD

**Issue by GitRon** [mbi/django-simple-captcha#81]
Hi guys,

in this file: https://github.com/mbi/django-simple-captcha/blob/master/captcha/locale/de/LC_MESSAGES/django.po are two spelling mistakes.

The correct German is: "Ungültiges CAPTCHA" and "Dieses Feld wird benötigt."

The third one "Spiel das CAPTCHA als Audiodatei ab." is not wrong but very colloquial. I would suggest "CAPTCHA als Audiodatei abspielen."

Best,
Ron

**Comment by mbi** [comment]
Thanks, fixed the po file.

**Comment by GitRon** [comment]
Perfect! Vielen Dank ;)
