### ISSUE TITLE
Multiple different captcha widgets with different configurations

### ISSUE THREAD

**Issue by asyncee** [mbi/django-simple-captcha#87]
Hello and thank you for this application.

Few weeks ago we have faced a problem of using captcha on our site. The use case is following: on desktop version of the site we needed to use default captcha widget, and on mobile devices - same widget but with different settings (font size, width, height).

As there are no possibility to use different configurations for captcha widgets, so i implemented it in an extension: https://github.com/asyncee/catpcha_extended

Extension is very simple - it overrides main view and adds possibility to load captcha widget settings through CAPTCHA_EXTENDED setting, so you can use different widgets like so:

    CAPTCHA_EXTENDED = {
        'large': {
            'CAPTCHA_IMAGE_SIZE': (480, 50),
            'CAPTCHA_FONT_SIZE': 40,
        }
    }

    from captcha_extended.fields import CaptchaField

    class MobileCommentForm(forms.Form):
        captcha = CaptchaField(config='large')

We use this extension in a number of our projects, but it would be nice if you can merge this implementation in django-simple-captcha, so any person can use it by default.

**Comment by mbi** [comment]
This looks interesting. Do you think you could send a pull request?

**Comment by asyncee** [comment]
Yes, i can, but the code from extension library must be adapted, also application configuration needs to be changed to bring support for different configurations (possibly introducing backwards-incompatible changes).

I will try to do that as soon as possible and send a PR.

**Comment by asyncee** [comment]
I have updated the code, so you can see it in branch: https://github.com/asyncee/django-simple-captcha/tree/captcha-extended

Thought there are ability to configure any number of different captchas, the code needs refactoring, documentation and tests. Also, i don't know what is your strategy on backward compatibility, so for now i tried to keep configuration compatible with older version, so all configuration in ``settings.py`` considered default, but extended with ConfigWrapper class.

I think it is early to create a PR, because feature and code needs your review/cleanup (maybe).

Also i updated test project, so you can test new captcha on the homepage.

**Comment by asyncee** [comment]
Closing, because looks like this functionality is not interesting for any one.
