### ISSUE TITLE
runnserver works fine but apache not

### ISSUE THREAD

**Issue by ysrotciv** [mbi/django-simple-captcha#91]
apache2.2 + django1.8

After I add django-simple-captcha to this project

when I start server by:

python manage.py runserver 0.0.0.0:8000

everything goes fine

but when I start it by apache

It shows the error: "The _imagingft C module is not installed."

**Comment by mbi** [comment]
The error says it all, you need to install PIL or Pillow in the same (virtual) environment that mod_wsgi resides in.
