### ISSUE TITLE
The _imagingft C module is not installed

### ISSUE THREAD

**Issue by martinsam** [mbi/django-simple-captcha#92]
Ubuntu 14.10 (OVH VPS).

/env/local/lib/python2.7/site-packages/PIL/ImageFont.py in __getattr__, line 42

Pillow it's ok . (pip install pillow).

On MacOS is work fine but not with production Ubuntu server .

**Comment by mbi** [comment]
The FT thing in the error stands for freetype.

The [installation documentation](http://django-simple-captcha.readthedocs.org/en/latest/usage.html#installation) has this covered. Anyway, this should help: 

    apt-get -y install libz-dev libjpeg-dev libfreetype6-dev python-dev

…then uninstall and reinstall Pillow.

**Comment by martinsam** [comment]
apt-get -y install libz-dev libjpeg-dev libfreetype6-dev python-dev

All are already installed.
