### ISSUE TITLE
pip install django-simple-captcha==0.4.6 error

### ISSUE THREAD

**Issue by murdav** [mbi/django-simple-captcha#96]
Hello,

I was trying to install django-simple-captcha using

    pip install django-simple-captcha==0.4.6

But I got

Could not find a version that satisfies the requirement django-simple-captcha==0.4.6 (from -r /var/www/gloweb_dev/gloweb/requirements/base.txt (line 20)) (from versions: 0.3.1, 0.3.1, 0.3.2, 0.3.2, 0.3.3, 0.3.3, 0.3.4, 0.3.4, 0.3.6, 0.3.6, 0.3.7, 0.3.7, 0.3.8, 0.3.8, 0.4.0, 0.4.0, 0.4.1, 0.4.1, 0.4.2, 0.4.2, 0.4.3, 0.4.3, 0.4.4, 0.4.4, 0.4.5, 0.4.5, 0.2.0, 0.2.0, 0.3.0, 0.3.0)

There is twice 0.4.5, instead of 0.4.6

D

**Comment by mbi** [comment]
Is your pip up to date? Are you using the default pypi repository? I'm seeing 0.4.6 all right:
```
(.venv)  ⮀ ~ ⮀ pip install django-simple-captcha==0.4.7
Collecting django-simple-captcha==0.4.7
  Could not find a version that satisfies the requirement django-simple-captcha==0.4.7 
(from versions: 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.6, 0.3.7, 0.3.8, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.4.5, 0.4.6)
```

**Comment by murdav** [comment]
Thanks for replying.
I'm using the default repo, but my PIP is not the latest version. I never thought something similar. 

D
