### ISSUE TITLE
Tests fail for Django 1.9

### ISSUE THREAD

**Issue by brianmay** [mbi/django-simple-captcha#99]
Lots of the following error:

TemplateSyntaxError: 'url' is not a valid tag or filter in tag library 'future'

**Comment by mbi** [comment]
There is a Django 1.9 branch, I'll merge it as soon as 1.9 final is released.

**Comment by brianmay** [comment]
Thanks!

**Comment by mbi** [comment]
just released 0.4.7 supporting django 1.7 – 1.9
